blank_issues_enabled: false
contact_links:
  - name: LI.FI Support
    url: https://help.li.fi/hc/en-us/requests/new
    about: For general LI.FI questions unrelated to the customized token list, please use our support channels.
